services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app/backend
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    working_dir: /app/backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 120s
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000/query
      - PYTHONUNBUFFERED=1
    volumes:
      - ./frontend:/app/frontend
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    working_dir: /app/frontend
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge